configure.ac: fix hard setting of CFLAGS
Daniel Danzberger reports:

Hi,

the current configure.ac overrides CFLAGS. This causes the following
error when running ./configure:

checking for pthread_create in -lpthread... no
configure: error: not found

Even if libpthread is available. A look in config.log shows:

cc1: note: someone does not honour COPTS correctly, passed 0 times
/work/openwrt/staging_dir/toolchain-arm_mpcore+vfp_gcc-4.6-linaro_uClibc-0.9.33.2_eabi/lib/gcc/arm-openwrt-linux-uclibcgnueabi/4.6.4/../../../../arm-openwrt-linux-uclibcgnueabi/bin/ld:
error: conftest uses VFP register arguments, /tmp/ccW5XZlm.o does not

This occurs when configure tires to compile the test program for
libpthread.
The error is caused of some missing CFLGAS needed for this architecture.
They were passed by the buildroot, but overriden in the configure.ac.

The attached little patch solves the issue, please apply.